### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Zethson** [ivirshup/anndata-paper#18]
Hey,

random feedback:
"A noteworthy design choice means is that we do not follow columnar (or “variable major”) data storage as for tidy-data and DataFrames. "

> means is

Think you can omit the means here? Reads weird to me.

You mentioned that you are not aware of any non comp bio related packages using anndata. Might be worth to double check by looking at all dependents: https://github.com/theislab/anndata/network/dependents?package_id=UGFja2FnZS01MDAyMDc2NQ%3D%3D

Was happy to see Muon, MuData and efforts for EHR analysis mentioned.

The frequent `...` in the author contributions confused me, especially just before a new sentence begins.

Enjoy the swift and highly automated JOSS submission process :) I am still astonished by how smoothly it works.
Cheers

**Comment by falexwolf** [comment]
Thanks a ton for the detailed read, Lukas! The text isn't 100% polished, yet; will fix the issues you mention.

Good that you point it out, but I indeed didn't find anything evident non-bio in the dependents list.

Can we add any sort of reference for the EHR efforts?

**Comment by Zethson** [comment]
> Can we add any sort of reference for the EHR efforts?

https://github.com/theislab/ehrapy/tree/development

But no releases, paper drafts or other things yet. You can link to the GH repository if you want and I can set the development branch as default branch so that people see activity.

I'll likely send you a short status report about the EHR efforts at the end of the year.

**Comment by falexwolf** [comment]
Cool, thank you! I think it'd make sense to link to the repository so that people see where this is being worked on.

**Comment by falexwolf** [comment]
See here: https://github.com/ivirshup/anndata-paper/pull/19
