### ISSUE TITLE
Phil’s feedback

### ISSUE THREAD

**Issue by flying-sheep** [ivirshup/anndata-paper#20]
- [x] Abstract
  “minimal” isn’t necesarily a good sell. I’d say it’s designed around the 2D shape and therefore especially user friendly if your use case is 2D biased (such as scRNA-Seq)
- Fig 1
  - [x] ~~a) Looks like the obsm matrices all have to have the same secondary dimension length. How can we edit the figures?~~
  - [x] b) “response variable learned from X”  is just an example. `obs` can also hold prior knowledge. Maybe we should be more generic here (like we are in a, d and e) or signal that we’re discussing example uses in b and c.
  - [x] d) could benefit from an example
- generally
  - [x] `AnnData` the class vs `anndata` the package/project aren’t always used consistently
- The on disk representation
  - [x] We should definitely mention that designing it this well and python-independent has a) let other languages interface with it, b) inspired viewers like cellxgene and c) led to HCA distributing files in the format (probably as a conseqence of a and the usefulness of the format)

I’m happy to contribute with edits, for today just feedback. (Especially I’ll of course handle my contribs)

**Comment by falexwolf** [comment]
## Abstract 

> “minimal” isn’t necesarily a good sell. I’d say it’s designed around the 2D shape and therefore especially user friendly if your use case is 2D biased (such as scRNA-Seq)

The logic is the following and should be made more evident if it's not: the 2D aspect is entirely captured in the term "matrix" (rank 2 tensor ~ 2d array), already in the title.

I agree that in the sentence in question "minimal additional structure that enables storing data matrix annotations" it's not becoming very clear that it means "minimal additional structure in addition to the structure needed to represent a matrix". I've made a few tries to come up with a concise way of stating this but wasn't very successful.

How about one does this instead? https://github.com/ivirshup/anndata-paper/pull/22/commits/c5a89999fb4b44b9f302db262509136bb7c039cc

## Figure 1

* This is an adobe illustrator file that Isaac maintains; I'd personally say that things will get too messy when trying to indicate that the shapes of obsm can vary; to me, it's a tiny detail that's OK as an abstraction that keeps the figure clean. Hence, I'd suggest to keep as is, but of course don't mind if you want to give it a try.
* https://github.com/ivirshup/anndata-paper/pull/22/commits/e04813121ec9025c1b51653a95b1e548e283e083
* https://github.com/ivirshup/anndata-paper/pull/22/commits/8de2bb0238113155819aaec08b2ec1df30dfeb4e

## Generally

Tried to be consistent and additionally introduced styling anndata as text and `AnnData` as code, but will give it another readthrough trying to make sure it's all consistent.

## On disk

Tried to address this here: https://github.com/ivirshup/anndata-paper/pull/22/commits/7fd78bf63de1caf894f9af1def9f5f0af5b47cf5

**Comment by flying-sheep** [comment]
I like your changes in #22!

**Comment by falexwolf** [comment]
Okie, will merge https://github.com/ivirshup/anndata-paper/pull/22 then!
